Automatically create new user on (potential) Sandbox reset.
bunq/tinker_php pull request #12
Opened 2018-03-26 15:37 UTC by JordyHeemskerk

(bunq/tinker_php#11)

2018-03-26 15:47 UTC, OGKevin requested changes
Some minor refactor requests.

2018-03-26 15:47 UTC, OGKevin commented on src/BunqLib.php
> +            if (BunqEnumApiEnvironmentType::SANDBOX()->equals($this->environment)
Extract this in its own method for better readability. 

```
private function handleForbiddenException(ForbiddenException $exception)
{
   // the code inside the catch block 
}

```

2018-03-26 15:47 UTC, OGKevin commented on src/BunqLib.php
> +                && strpos($forbiddenException->getMessage(), self::ERROR_INSUFFICIENT_AUTHENTICATION) !== false
Hmm we normally use REGEX for these type of lookups instead of `strpos`.

2018-03-26 17:58 UTC, OGKevin requested changes
One small change.

2018-03-26 17:58 UTC, OGKevin commented on src/BunqLib.php
> +            && preg_match(self::REGEX_ERROR_INSUFFICIENT_AUTHENTICATION, $forbiddenException->getMessage())
```
preg_match(self::REGEX_ERROR_INSUFFICIENT_AUTHENTICATION, $forbiddenException->getMessage()) ===  self::REGEX_MATCH_FOUD
```

where `REGEX_MATCH_FOUD = 1`

> preg_match() returns 1 if the pattern matches given subject, 0 if it does not, or FALSE if an error occurred.
http://php.net/manual/en/function.preg-match.php

2018-03-26 21:46 UTC, JordyHeemskerk commented on src/BunqLib.php
> +            && preg_match(self::REGEX_ERROR_INSUFFICIENT_AUTHENTICATION, $forbiddenException->getMessage())
That is not required as:
```
php > if (1) echo "true" . PHP_EOL;
true
php > if (0) echo "true" . PHP_EOL;
php > if (false) echo "true" . PHP_EOL;

2018-03-27 08:08 UTC, OGKevin commented on src/BunqLib.php
> +            && preg_match(self::REGEX_ERROR_INSUFFICIENT_AUTHENTICATION, $forbiddenException->getMessage())
Yes, but this is some php magic ✨ and unfortunately we don't use this e.g.

https://github.com/bunq/sdk_php/blob/c0895dc40c7076b103bbb931ec69068e4daf94f0/src/Util/InstallationUtil.php#L282-L289

2018-03-27 14:16 UTC, OGKevin approved these changes
LGTM

2018-03-27 14:16 UTC, merged

2018-03-27 14:16 UTC, OGKevin commented
@andrederoos