Request money on Sandbox if balance zero. (bunq/tinker_php#14)
bunq/tinker_php pull request #15
Opened 2018-04-04 21:40 UTC by JordyHeemskerk

2018-04-05 11:34 UTC, OGKevin requested changes
Some minor changes.

2018-04-05 11:34 UTC, OGKevin commented on src/BunqLib.php
> +use Habitat\Environment\Environment;
This can be removed right ? :P

2018-04-05 11:34 UTC, OGKevin commented on src/BunqLib.php
> +        $this->requestSpendingMoneyIfNeeded();
TODO: bunq/sdk_php#122

After sdk update.

2018-04-05 11:34 UTC, OGKevin commented on src/BunqLib.php
> +        if (BunqEnumApiEnvironmentType::SANDBOX()->equals($this->environment)
This logic can be extracted in its own separate method.

2018-04-12 12:20 UTC, JordyHeemskerk commented
@OGKevin moving UserContext refresh to new issue. Implemented comments.

2018-04-12 17:19 UTC, OGKevin approved these changes

2018-04-12 17:19 UTC, merged

2018-04-12 17:19 UTC, OGKevin commented
@andrederoos

2024-02-28 01:51 UTC, einfachdavid89 commented on src/BunqLib.php
> +use Habitat\Environment\Environment;
Ja