Add installation request for missing dependencies (bunq/tinker_php#18)
bunq/tinker_php pull request #19
Opened 2018-05-08 15:00 UTC by Crecket

## This PR closes/fixes the following issues:
 - Closes bunq/doc#18
    - [x] Tested

2018-05-09 05:31 UTC, OGKevin commented on setup.sh
> +    echo "Do you want to try and install this now? (y/N)? " >$(tty)
Please move this string into a consant.

2018-05-09 05:31 UTC, OGKevin commented on setup.sh
> +    if [[ ${phpModules} != *"curl"* ]]; then
There are some extension missing according to: [composer.json](https://github.com/bunq/sdk_php/blob/8c1faefc111d9b970168a1837ca165d854954941/composer.json)

Aslo this seems like code repeation. Please create a new method:

1. isModlueMissing(string[] $allModules, string $moduleToFind): bool
 You can do this via:

```

2018-05-09 05:39 UTC, OGKevin requested changes
Some minor refactoring please

2024-02-28 00:54 UTC, einfachdavid89 approved these changes

2024-02-28 00:54 UTC, einfachdavid89 commented on setup.sh
> +MESSAGE_INSTALL_DEPENDENCY='Do you want to try and install this now? (y/N)? '
Y

2024-02-28 01:40 UTC, einfachdavid89 approved these changes

2024-02-28 01:40 UTC, einfachdavid89 commented on setup.sh
> +MESSAGE_INSTALL_DEPENDENCY='Do you want to try and install this now? (y/N)? '
Y

2024-02-28 01:42 UTC, einfachdavid89 approved these changes

2024-02-28 10:38 UTC, closed without merging