Bunq/tinker_php#23-update sdk version to major 1
bunq/tinker_php pull request #24
Opened 2018-08-17 11:56 UTC by OGKevin

2018-08-20 09:06 UTC, OGKevin commented
@JordyHeemskerk

2018-08-20 09:20 UTC, JordyHeemskerk requested changes

2018-08-20 09:20 UTC, JordyHeemskerk commented on src/BunqLib.php
> +            null,
Missing comment

2018-08-20 09:20 UTC, JordyHeemskerk commented on src/BunqLib.php
> +            [new CardPinAssignment('PRIMARY', null, $monetaryAccount->getId())]
Also missing comment on what argument is used for.

2018-08-20 11:53 UTC, OGKevin commented on src/BunqLib.php
> +            [new CardPinAssignment('PRIMARY', null, $monetaryAccount->getId())]
what argument i dont follow ? No other arguments in this file has this.

2018-08-20 20:21 UTC, JordyHeemskerk submitted a review, later dismissed

2018-08-20 20:21 UTC, JordyHeemskerk commented on src/BunqLib.php
> +                    'PRIMARY',
extract const

2018-08-21 08:10 UTC, JordyHeemskerk approved these changes

2018-08-21 08:11 UTC, merged

2018-08-21 08:11 UTC, OGKevin commented
@andrederoos